- name: Disable default nginx
  ansible.builtin.shell: dnf module disable nginx -y

- name: Enable Nginx 24 version
  ansible.builtin.shell: dnf module enable nginx:1.24 -y

- name: Install Nginx
  ansible.builtin.dnf:
    name: nginx
    state: latest

- name: Copy nginx config file
  ansible.builtin.copy:
    src:  nginx.conf
    dest: /etc/nginx/nginx.conf

- name: Setup App Pre-reqs. #pre-reqs from common
  ansible.builtin.include_role:
    name: common
    tasks_from: app-prereq

- name: Enable and Start Nginx
  ansible.builtin.systemd_service:
    state: restarted
    name: nginx
    enabled: true #enable nginx