- name: Copy MongoDB repo
  ansible.builtin.copy:
    src: rabbitmq.repo
    dest: /etc/yum.repos.d/rabbitmq.repo

- name: Install mongoDB
  ansible.builtin.dnf:
    name: mongodb-org
    state: latest


- name: Update MongoDB Conf file
  ansible.builtin.replace:
    path: /etc/mongod.conf
    regexp: '127.0.0.1'
    replace: '0.0.0.0'


- name:  Start MongoDB Service
  ansible.builtin.systemd_service:
    name: mongod
    state: restarted
    enabled: true