
- name:  Install Golang
  ansible.builtin.dnf:
    name: golang
    state: latest

- name: Setup App Pre-reqs.
  ansible.builtin.include_role:
    name: common
    tasks_from: app-prereq

- name:  Download Golang dependencies
  ansible.builtin.shell: go mod init dispatch ; go get ; go build;
  args:
    chdir: "{{ app_path }}"


- name: Load schema
  ansible.builtin.include_role:
    name: common
    tasks_from: schema
  when: schema_setup is defined #define in vars>main


- name: Setup App SystemD.
  ansible.builtin.include_role:
    name: common
    tasks_from: systemd


#source common.sh
#component=payment
#app_path=/app
#
#PRINT Install GoLang
#dnf install golang -y &>>$LOG_FILE
#STAT $?
#
#APP_PREREQ
#
#cd /app
#PRINT download the dependencies  build the software
#go mod init dispatch  &>>$LOG_FILE
#go get                &>>$LOG_FILE
#go build              &>>$LOG_FILE
#STAT $?
#
#SYSTEMD_SETUP