- name: Copy Repo File
  ansible.builtin.copy:
      src: rabbitmq.repo
      dest: /etc/yum.repos.d/rabbitmq.repo

- name: Install rabbitmq server
  ansible.builtin.dnf:
    name: rabbitmq-server
    state: latest

- name: Start Rabbitmq service
  ansible.builtin.systemd_service:
    name: rabbitmq-server
    enabled: yes

- name: Create application user
  ansible.builtin.shell: rabbitmqctl add_user roboshop roboshop123; rabbitmqctl set_permissions -p / roboshop ".*" ".*" ".*";




#cp rabbitmq.repo /etc/yum.repos.d/rabbitmq.repo
#dnf install rabbitmq-server -y
#systemctl enable rabbitmq-server
#systemctl restart rabbitmq-server
#
#rabbitmqctl add_user roboshop roboshop123
#rabbitmqctl set_permissions -p / roboshop ".*" ".*" ".*"